services:
  postgres:
    image: postgres:16
    ports:
      - "15432:5432"
    volumes:
     - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
  qdrant:
    image: qdrant/qdrant:v1.8.0
    ports:
      - "6333:6333"
    volumes:
     - ./qdrant_data:/qdrant/storage:z
  sonic:
    image: valeriansaliou/sonic:v1.4.8
    ports:
      - "1491:1491"
    volumes:
      - ./sonic_data:/var/lib/sonic/store:z
      - ./sonic_config.cfg:/etc/sonic.cfg:ro
  document_storage:
    build: document_storage
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:secretpassword@postgres:15432/postgres
      - QDRANT_CONNECTION_STRING=http://qdrant:6333

    depends_on:
      - postgres
      - qdrant