services:
  postgres:
    image: postgres:16
    ports:
      - "15432:5432"
    volumes:
     - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
  qdrant:
    image: qdrant/qdrant:v1.8.0
    ports:
      - "6333:6333"
    volumes:
     - ./qdrant_data:/qdrant/storage:z
  document_storage:
    build: document_storage
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:secretpassword@postgres:15432/postgres
      - QDRANT_CONNECTION_STRING=http://qdrant:6333

    depends_on:
      - postgres
      - qdrant