services:
  postgres:
    image: postgres:16
    ports:
      - "15432:5432"
    volumes:
     - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
  qdrant:
    image: qdrant/qdrant:v1.8.0
    ports:
      - "6333:6333"
    volumes:
     - ./qdrant_data:/qdrant/storage:z